apiVersion: v1
kind: ConfigMap
metadata:
  name: sharding-proxy-config
  namespace: default
  labels:
    k8s-app: sharding-proxy
data:
  config-sharding.yaml: |-
    schemaName: iot_smarthome_platform
    dataSources:
      ds:
        url: jdbc:mysql://172.31.1.165/iot_smarthome_platform?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
        username: root
        password: Znjj@Box2017
        connectionTimeoutMilliseconds: 30000
        idleTimeoutMilliseconds: 60000
        maxLifetimeMilliseconds: 1800000
        maxPoolSize: 50
    shardingRule:
      tables:
        t_report_device_info:
          actualDataNodes: ds.t_report_device_info_$->{0..15}
          tableStrategy:
            standard:
              shardingColumn: ctei
              preciseAlgorithmClassName: com.iflytek.iot.sharding.algorithm.CommonPreciseShardingAlgorithm
        t_scene:
          actualDataNodes: ds.t_scene_$->{0..31}
          tableStrategy:
            standard:
              shardingColumn: user_id
              preciseAlgorithmClassName: com.iflytek.iot.sharding.algorithm.CommonPreciseShardingAlgorithm
        t_user_info:
          actualDataNodes: ds.t_user_info_$->{0..15}
          tableStrategy:
            standard:
              shardingColumn: ty_account
              preciseAlgorithmClassName: com.iflytek.iot.sharding.algorithm.CommonPreciseShardingAlgorithm
        t_device_info:
          actualDataNodes: ds.t_device_info_$->{0..31}
          tableStrategy:
            standard:
              shardingColumn: device_id
              preciseAlgorithmClassName: com.iflytek.iot.sharding.algorithm.CommonPreciseShardingAlgorithm
        t_room_info:
          actualDataNodes: ds.t_room_info_$->{0..31}
          tableStrategy:
            standard:
              shardingColumn: iot_account
              preciseAlgorithmClassName: com.iflytek.iot.sharding.algorithm.CommonPreciseShardingAlgorithm
        t_house_info:
          actualDataNodes: ds.t_house_info_$->{0..15}
          tableStrategy:
            standard:
              shardingColumn: iot_account
              preciseAlgorithmClassName: com.iflytek.iot.sharding.algorithm.CommonPreciseShardingAlgorithm
        t_user_im_token:
          actualDataNodes: ds.t_user_im_token_$->{0..15}
          tableStrategy:
            standard:
              shardingColumn: iot_account
              preciseAlgorithmClassName: com.iflytek.iot.sharding.algorithm.CommonPreciseShardingAlgorithm
  server.yaml: |-
    authentication:
      users:
        root:
          password: Znjj@Box2017
        sharding:
          password: Znjj@Box2017
          authorizedSchemas: sharding_db
---