version: '3'
services:
  elasticsearch-single:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    container_name: elasticsearch-single
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://{ip}:9200
      - ELASTICSEARCH_HOSTS=http://{ip}:9200
    ports:
      - "5601:5601"
    networks:
      - esnet
networks:
  esnet: