version: '3'
services:
  kibana:
    image: registry.cn-hangzhou.aliyuncs.com/elk-stack/kibana:7.4.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://172.31.131.9:9200
      - ELASTICSEARCH_HOSTS=http://172.31.131.9:9200
    ports:
      - "5601:5601"
    networks:
      - esnet
networks:
  esnet:
