version: '3'
services:
  filebeat:
    image: registry.cn-hangzhou.aliyuncs.com/elk-stack/alpine-filebeat:7.4.2
    container_name: filebeat
    environment:
      - ELASTICSEARCH_URL=http://172.31.131.9:9200
      - ELASTICSEARCH_HOSTS=http://172.31.131.9:9200
     volumes:
          - ./filebeat-kafka.yml:/filebeat/filebeat.yml
    networks:
      - esnet
networks:
  esnet: