apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-application
  namespace: elk
data:
  logstash.conf: |-
    input {
      kafka {
        bootstrap_servers => "172.31.205.22:9092"
        topics => ["k8s-test"]
        type => "kafka-input"
        codec => "json"
      }
    }
    output {
      stdout {
        codec => rubydebug
      }
    }
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
    xpack.monitoring.enabled: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-application
  namespace: elk
spec:
  template:
    metadata:
      labels:
        app: logstash-application
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/shalousun/logstash
        name: logstash-application
        ports:
        - name: logstash
          containerPort: 5044
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true
        args:
        - -f
        - /usr/share/logstash/pipeline/logstash.conf
        resources:
          limits:
            memory: 512Mi
            cpu: "200m"
          requests:
            memory: 512Mi
            cpu: "200m"
      volumes:
      - name: pipeline
        configMap:
          name: logstash-application
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: config
        configMap:
          name: logstash-application
          items:
          - key: logstash.yml
            path: logstash.yml
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-application
  namespace: elk
  labels:
    app: logstash-application
spec:
  selector:
    app: logstash-application
  ports:
  - name: logstash
    port: 5044
    targetPort: 5044
    protocol: TCP

