# Used to collect logs from kubernates pods
#
# Example usage: kubectl create -f <this_file>

# ------------------- Filebeat Config ------------------------------------- #
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.registry_file: /var/log/filebeat.registry
    processors:
      - add_cloud_metadata:
    fields_under_root: true
    fields:
      program: filebeat_k8s
      hostname: ${FILEBEAT_HOST:${HOSTNAME}}
    filebeat.prospectors:
      - input_type: log
        paths:
          - /var/log/containers/*service*.log
        symlinks: true
        tail_files: true
        json.message_key: log
        json.keys_under_root: true
        json.add_error_key: true
        max_lines: 1000
        negate: true
        multiline.pattern: '^\s*(\d{4}|\d{2})\-(\d{2}|[a-zA-Z]{3})\-(\d{2}|\d{4})'
        multiline.match: after
        document_type: k8s_log
    output.logstash:
      hosts: [ "${LOGSTASH_HOST}:${LOGSTASH_PORT}" ]
---
# ------------------- SpringBoot Application Service ---------------------- #
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      name: filebeat
  template:
    metadata:
      labels:
        name: filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: filebeat
        image: registry.cn-hangzhou.aliyuncs.com/shalousun/filebeat-kafka:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
            - name:  LOGSTASH_HOST
              value: "172.31.205.24"
            - name:  LOGSTASH_PORT
              value: "5044"
        volumeMounts:
        - name: filebeat-config
          mountPath: /filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filebeat-config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
