version: '3'
services:
  kafka-eagle:
    container_name: kafka-eagle
    image: registry.cn-hangzhou.aliyuncs.com/shalousun/kafka-eagle:1.4.6
    ports:
      - "8048:8048"
    environment:
      KAFKA_ZOOKEEPER_HOSTS: <IP:PORT>
      DB_HOST: <IP:PORT>
      DB_USER: <USER>
      DB_PASSWORD: <PASSWORD>