version: '3'
services:
  kafka-eagle:
    container_name: kafka-eagle
    image: registry.cn-hangzhou.aliyuncs.com/shalousun/kafka-eagle:1.4.6
    ports:
      - "8048:8048"
    volumes:
      - ./system-config.properties:/opt/kafka-eagle/conf/system-config.properties
      - ./log4j.properties:/opt/kafka-eagle/conf/log4j.properties
    networks:
      - eaglenet
networks:
  eaglenet: