apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  MYSQL_URL: jdbc:mysql://192.168.237.1:3306/soul?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false